import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { parseFitsBinTable } from '../../../tools/parsers/desiFits';

/**
 * `tests/fixtures/desi/qso_ngc_head6.fits` (9,270 bytes) was generated by
 * the controller on 2026-07-07 via a live 32 KB HTTP range request against
 * DESI DR1's `QSO_NGC_clustering.dat.fits`
 * (https://data.desi.lbl.gov/public/dr1/survey/catalogs/dr1/LSS/iron/LSScats/v1.5/QSO_NGC_clustering.dat.fits,
 * see `tools/utils/io/rawDataRegistry.ts`'s `desi.qso` entry) —
 * primary header + BINTABLE extension header + the first 6 data rows, with
 * the extension's `NAXIS2` card patched from its true (much larger) row
 * count down to `6` so the fixture stays small while keeping every header
 * card and the first 6 rows byte-identical to the upstream file. It is
 * checked in verbatim and must never be regenerated or hand-edited — a
 * byte-for-byte real FITS file is what makes this test worth having; a
 * synthesized one would only test our own assumptions about the format.
 */
const FIXTURE_PATH = join(process.cwd(), 'tests/fixtures/desi/qso_ngc_head6.fits');

function loadFixture(): ArrayBuffer {
  const bytes = readFileSync(FIXTURE_PATH);
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

// ─── Synthetic FITS builder (in-memory, for the two throw-path tests) ──────
//
// Real FITS files pad every header to a whole number of 2880-byte blocks
// (36 cards × 80 chars). This mirrors `glade.test.ts`'s `makeFixture` idiom
// of writing a synthetic fixed-width record byte-by-byte via a small `put`
// helper — here the "fixed width" unit is the 80-char FITS card instead of
// a column range.

const CARD_SIZE = 80;
const BLOCK_SIZE = 2880;

/** Format one fixed-format FITS card: `KEYWORD = value`, padded/truncated to 80 chars. */
function fitsCard(keyword: string, rawValue: string): string {
  return `${keyword.padEnd(8)}= ${rawValue}`.padEnd(CARD_SIZE, ' ').slice(0, CARD_SIZE);
}

/** Quote a string value the way a FITS card expects, e.g. fitsCard('XTENSION', fitsStr('BINTABLE')). */
function fitsStr(s: string): string {
  return `'${s}'`;
}

/** Pack a list of pre-formatted 80-char cards into an END-terminated, block-padded header. */
function packHeaderBlock(cards: string[]): Uint8Array {
  const text = [...cards, 'END'.padEnd(CARD_SIZE, ' ')].join('');
  const blocks = Math.ceil(text.length / BLOCK_SIZE);
  return new TextEncoder().encode(text.padEnd(blocks * BLOCK_SIZE, ' '));
}

function concatBuffers(...parts: Uint8Array[]): ArrayBuffer {
  const total = parts.reduce((sum, p) => sum + p.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out.buffer;
}

/** Minimal primary header: SIMPLE + NAXIS=0 (no primary data, matching every real DESI LSS file). */
function primaryHeaderBlock(): Uint8Array {
  return packHeaderBlock([fitsCard('SIMPLE', 'T'), fitsCard('NAXIS', '0')]);
}

/** Primary header + a BINTABLE extension whose single column has an unsupported TFORM ('C'). */
function buildUnsupportedTformBuffer(): ArrayBuffer {
  const extensionBlock = packHeaderBlock([
    fitsCard('XTENSION', fitsStr('BINTABLE')),
    fitsCard('NAXIS1', '1'),
    fitsCard('NAXIS2', '1'),
    fitsCard('TFIELDS', '1'),
    fitsCard('TTYPE1', fitsStr('FOO')),
    fitsCard('TFORM1', fitsStr('C')),
  ]);
  return concatBuffers(primaryHeaderBlock(), extensionBlock);
}

/** Primary header only, buffer ends immediately after — no second HDU at all. */
function buildNoExtensionBuffer(): ArrayBuffer {
  // Copy via concatBuffers rather than slicing `.buffer` directly: a generic
  // Uint8Array's `.buffer` is `ArrayBuffer | SharedArrayBuffer` under this TS
  // lib config, while concatBuffers' `new Uint8Array(n).buffer` is a plain
  // `ArrayBuffer`. A one-element concat is exactly the copy we want.
  return concatBuffers(primaryHeaderBlock());
}

describe('parseFitsBinTable', () => {
  it('parses the QSO fixture header: rowLengthBytes 105, rowCount 6, 14 columns', () => {
    const table = parseFitsBinTable(loadFixture());
    expect(table.rowLengthBytes).toBe(105);
    expect(table.rowCount).toBe(6);
    expect(table.columns.length).toBe(14);
  });

  it('column byte offsets are contiguous and sum to rowLengthBytes', () => {
    const table = parseFitsBinTable(loadFixture());
    // Contiguity: each column starts exactly where the previous one ended.
    let expectedOffset = 0;
    for (const col of table.columns) {
      expect(col.byteOffset).toBe(expectedOffset);
      expectedOffset += col.byteLength;
    }
    const last = table.columns[table.columns.length - 1]!;
    expect(last.byteOffset + last.byteLength).toBe(table.rowLengthBytes);
  });

  it('finds RA, DEC, Z as f64 (TFORM D), TARGETID as i64 (TFORM K), PHOTSYS as 1A', () => {
    const table = parseFitsBinTable(loadFixture());
    const byName = new Map(table.columns.map((c) => [c.name, c]));
    expect(byName.get('RA')?.form).toBe('D');
    expect(byName.get('DEC')?.form).toBe('D');
    expect(byName.get('Z')?.form).toBe('D');
    expect(byName.get('TARGETID')?.form).toBe('K');
    expect(byName.get('PHOTSYS')?.form).toBe('1A');
  });

  it('throws naming the offending TFORM on an unsupported column type', () => {
    expect(() => parseFitsBinTable(buildUnsupportedTformBuffer())).toThrow(/TFORM "C"/);
  });

  it('throws on a buffer with no BINTABLE extension', () => {
    expect(() => parseFitsBinTable(buildNoExtensionBuffer())).toThrow();
  });
});
