import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  parseFitsBinTable,
  parseDesiClustering,
  type DesiTracer,
} from '../../../tools/parsers/desiFits';
import { DESI_TRACER_DISPLAY } from '../../../tools/parsers/desiTracerDisplay';
import { DESI_TRACER_CLASS } from '../../../src/data/galaxyCatalog/sourceClass';
import { Source } from '../../../src/data/sources';
import { redshiftToDistanceMpc } from '../../../src/utils/math/redshiftToDistanceMpc';

/**
 * `tests/fixtures/desi/qso_ngc_head6.fits` (9,270 bytes) was generated by
 * the controller on 2026-07-07 via a live 32 KB HTTP range request against
 * DESI DR1's `QSO_NGC_clustering.dat.fits`
 * (https://data.desi.lbl.gov/public/dr1/survey/catalogs/dr1/LSS/iron/LSScats/v1.5/QSO_NGC_clustering.dat.fits,
 * see `tools/utils/io/rawDataRegistry.ts`'s `desi.qso` entry) —
 * primary header + BINTABLE extension header + the first 6 data rows, with
 * the extension's `NAXIS2` card patched from its true (much larger) row
 * count down to `6` so the fixture stays small while keeping every header
 * card and the first 6 rows byte-identical to the upstream file. It is
 * checked in verbatim and must never be regenerated or hand-edited — a
 * byte-for-byte real FITS file is what makes this test worth having; a
 * synthesized one would only test our own assumptions about the format.
 */
const FIXTURE_PATH = join(process.cwd(), 'tests/fixtures/desi/qso_ngc_head6.fits');

function loadFixture(): ArrayBuffer {
  const bytes = readFileSync(FIXTURE_PATH);
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

// ─── Synthetic FITS builder (in-memory: throw-path + synthesized-row tests) ─
//
// Real FITS files pad every header to a whole number of 2880-byte blocks
// (36 cards × 80 chars). This mirrors `glade.test.ts`'s `makeFixture` idiom
// of writing a synthetic fixed-width record byte-by-byte via a small `put`
// helper — here the "fixed width" unit is the 80-char FITS card instead of
// a column range.

const CARD_SIZE = 80;
const BLOCK_SIZE = 2880;

/** Format one fixed-format FITS card: `KEYWORD = value`, padded/truncated to 80 chars. */
function fitsCard(keyword: string, rawValue: string): string {
  return `${keyword.padEnd(8)}= ${rawValue}`.padEnd(CARD_SIZE, ' ').slice(0, CARD_SIZE);
}

/** Quote a string value the way a FITS card expects, e.g. fitsCard('XTENSION', fitsStr('BINTABLE')). */
function fitsStr(s: string): string {
  return `'${s}'`;
}

/** Pack a list of pre-formatted 80-char cards into an END-terminated, block-padded header. */
function packHeaderBlock(cards: string[]): Uint8Array {
  const text = [...cards, 'END'.padEnd(CARD_SIZE, ' ')].join('');
  const blocks = Math.ceil(text.length / BLOCK_SIZE);
  return new TextEncoder().encode(text.padEnd(blocks * BLOCK_SIZE, ' '));
}

function concatBuffers(...parts: Uint8Array[]): ArrayBuffer {
  const total = parts.reduce((sum, p) => sum + p.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out.buffer;
}

/** Minimal primary header: SIMPLE + NAXIS=0 (no primary data, matching every real DESI LSS file). */
function primaryHeaderBlock(): Uint8Array {
  return packHeaderBlock([fitsCard('SIMPLE', 'T'), fitsCard('NAXIS', '0')]);
}

/** Primary header + a BINTABLE extension whose single column has an unsupported TFORM ('C'). */
function buildUnsupportedTformBuffer(): ArrayBuffer {
  const extensionBlock = packHeaderBlock([
    fitsCard('XTENSION', fitsStr('BINTABLE')),
    fitsCard('NAXIS1', '1'),
    fitsCard('NAXIS2', '1'),
    fitsCard('TFIELDS', '1'),
    fitsCard('TTYPE1', fitsStr('FOO')),
    fitsCard('TFORM1', fitsStr('C')),
  ]);
  return concatBuffers(primaryHeaderBlock(), extensionBlock);
}

/** Primary header only, buffer ends immediately after — no second HDU at all. */
function buildNoExtensionBuffer(): ArrayBuffer {
  // Copy via concatBuffers rather than slicing `.buffer` directly:
  // primaryHeaderBlock/packHeaderBlock's bare `: Uint8Array` return
  // annotations default to `Uint8Array<ArrayBufferLike>`, so `.buffer` is
  // `ArrayBuffer | SharedArrayBuffer` (even though TextEncoder.encode()
  // itself returns `Uint8Array<ArrayBuffer>` under this repo's libs).
  // concatBuffers' `new Uint8Array(n).buffer` is a plain `ArrayBuffer`,
  // and a one-element concat is exactly the copy we want.
  return concatBuffers(primaryHeaderBlock());
}

/** A well-formed header block that is not FITS: no SIMPLE card at all. */
function buildNotFitsBuffer(): ArrayBuffer {
  return concatBuffers(packHeaderBlock([fitsCard('NAXIS', '0')]));
}

/** Valid primary header followed by a non-table extension (XTENSION = 'IMAGE'). */
function buildImageExtensionBuffer(): ArrayBuffer {
  const extensionBlock = packHeaderBlock([
    fitsCard('XTENSION', fitsStr('IMAGE')),
    fitsCard('NAXIS', '0'),
  ]);
  return concatBuffers(primaryHeaderBlock(), extensionBlock);
}

// ─── Synthesized data-row builders (for the parseDesiClustering tests) ─────

/** One synthesized column: TTYPE name + a scalar TFORM the decoder supports. */
type SynthColumn = { name: string; form: 'D' | 'E' | 'K' };

const SYNTH_FORM_BYTES: Record<SynthColumn['form'], number> = { D: 8, E: 4, K: 8 };

/**
 * Build a complete in-memory FITS file: primary header, BINTABLE
 * extension header derived from `columns`, then `rows` encoded
 * big-endian (the FITS byte order). Cell values are `bigint` for K
 * columns and `number` for D/E — matching each row array positionally
 * to `columns`. No block padding after the data: the parser reads
 * exactly rowCount rows and never depends on trailing padding.
 */
function buildClusteringBuffer(columns: SynthColumn[], rows: (number | bigint)[][]): ArrayBuffer {
  const rowLength = columns.reduce((sum, c) => sum + SYNTH_FORM_BYTES[c.form], 0);
  const headerCards = [
    fitsCard('XTENSION', fitsStr('BINTABLE')),
    fitsCard('NAXIS1', String(rowLength)),
    fitsCard('NAXIS2', String(rows.length)),
    fitsCard('TFIELDS', String(columns.length)),
    ...columns.flatMap((c, i) => [
      fitsCard(`TTYPE${i + 1}`, fitsStr(c.name)),
      fitsCard(`TFORM${i + 1}`, fitsStr(c.form)),
    ]),
  ];
  const data = new Uint8Array(rows.length * rowLength);
  const view = new DataView(data.buffer);
  for (let r = 0; r < rows.length; r++) {
    let offset = r * rowLength;
    for (let c = 0; c < columns.length; c++) {
      const col = columns[c]!;
      const value = rows[r]![c]!;
      if (col.form === 'K') view.setBigInt64(offset, BigInt(value), false);
      else if (col.form === 'D') view.setFloat64(offset, Number(value), false);
      else view.setFloat32(offset, Number(value), false);
      offset += SYNTH_FORM_BYTES[col.form];
    }
  }
  return concatBuffers(primaryHeaderBlock(), packHeaderBlock(headerCards), data);
}

/**
 * BGS-shaped columns: positions uppercase (as on disk for every tracer),
 * flux columns lowercase (as on disk for BGS — this is what exercises the
 * parser's case-insensitive column lookup).
 */
const BGS_COLUMNS: SynthColumn[] = [
  { name: 'TARGETID', form: 'K' },
  { name: 'RA', form: 'D' },
  { name: 'DEC', form: 'D' },
  { name: 'Z', form: 'D' },
  { name: 'flux_g_dered', form: 'E' },
  { name: 'flux_r_dered', form: 'E' },
  { name: 'flux_z_dered', form: 'E' },
];

/** LRG/ELG/QSO-shaped columns: positions + ID only, no fluxes at all. */
const FLUXLESS_COLUMNS: SynthColumn[] = [
  { name: 'TARGETID', form: 'K' },
  { name: 'RA', form: 'D' },
  { name: 'DEC', form: 'D' },
  { name: 'Z', form: 'D' },
];

/** Expected synthetic magR for a fluxless tracer at redshift z. */
function syntheticMagR(tracer: Exclude<DesiTracer, 'BGS'>, z: number): number {
  const dL = (1 + z) * redshiftToDistanceMpc(z);
  return DESI_TRACER_DISPLAY[tracer].absMagR + 5 * Math.log10(dL * 1e5);
}

describe('parseFitsBinTable', () => {
  it('parses the QSO fixture header: rowLengthBytes 105, rowCount 6, 14 columns', () => {
    const table = parseFitsBinTable(loadFixture());
    expect(table.rowLengthBytes).toBe(105);
    expect(table.rowCount).toBe(6);
    expect(table.columns.length).toBe(14);
    // Primary header (1 block) + extension header (2 blocks) = 3 × 2880.
    expect(table.dataOffset).toBe(8640);
  });

  it('column byte offsets are contiguous and sum to rowLengthBytes', () => {
    const table = parseFitsBinTable(loadFixture());
    // Contiguity: each column starts exactly where the previous one ended.
    let expectedOffset = 0;
    for (const col of table.columns) {
      expect(col.byteOffset).toBe(expectedOffset);
      expectedOffset += col.byteLength;
    }
    const last = table.columns[table.columns.length - 1]!;
    expect(last.byteOffset + last.byteLength).toBe(table.rowLengthBytes);
  });

  it('finds RA, DEC, Z as f64 (TFORM D), TARGETID as i64 (TFORM K), PHOTSYS as 1A', () => {
    const table = parseFitsBinTable(loadFixture());
    const byName = new Map(table.columns.map((c) => [c.name, c]));
    expect(byName.get('RA')?.form).toBe('D');
    expect(byName.get('DEC')?.form).toBe('D');
    expect(byName.get('Z')?.form).toBe('D');
    expect(byName.get('TARGETID')?.form).toBe('K');
    expect(byName.get('PHOTSYS')?.form).toBe('1A');
  });

  it('throws naming the offending TFORM on an unsupported column type', () => {
    expect(() => parseFitsBinTable(buildUnsupportedTformBuffer())).toThrow(/TFORM "C"/);
  });

  it('throws on a buffer with no BINTABLE extension', () => {
    expect(() => parseFitsBinTable(buildNoExtensionBuffer())).toThrow();
  });

  it('throws "not a FITS file" when the primary header has no SIMPLE card', () => {
    expect(() => parseFitsBinTable(buildNotFitsBuffer())).toThrow(/not a FITS file/);
  });

  it('throws naming the wrong XTENSION when the first extension is not a BINTABLE', () => {
    expect(() => parseFitsBinTable(buildImageExtensionBuffer())).toThrow(
      /no BINTABLE extension.*XTENSION="IMAGE"/,
    );
  });
});

describe('parseDesiClustering', () => {
  // Row-0 literals of the real fixture, verified against the upstream
  // file at generation time (see the fixture provenance comment above).
  const QSO_ROW0_TARGETID = 39627540901396635n;
  const QSO_ROW0_RA = 159.24049207286527;
  const QSO_ROW0_DEC = -10.157311765959316;
  const QSO_ROW0_Z = 3.31353326666703;

  it('decodes row 0 of the QSO fixture to the pinned RA/DEC/Z', () => {
    const { records, skipped } = parseDesiClustering(loadFixture(), 'QSO');
    expect(records.length).toBe(6);
    expect(skipped).toBe(0);
    const rec = records[0]!;
    expect(rec.ra).toBe(QSO_ROW0_RA);
    expect(rec.dec).toBe(QSO_ROW0_DEC);
    expect(rec.z).toBe(QSO_ROW0_Z);
    expect(rec.spectroscopicZ).toBe(QSO_ROW0_Z);
    expect(rec.source).toBe(Source.DesiDeep);
  });

  it('QSO fixture row 0 synthesizes magnitudes from the tracer table', () => {
    const { records } = parseDesiClustering(loadFixture(), 'QSO');
    const rec = records[0]!;
    // Distance modulus at the pinned redshift: m = M + 5·log10(d_L/10pc),
    // with d_L = (1+z)·d_C and 1e5 the Mpc → 10 pc factor. The −25.5 /
    // 0.3 literals pin DESI_TRACER_DISPLAY.QSO's published values.
    const dL = (1 + QSO_ROW0_Z) * redshiftToDistanceMpc(QSO_ROW0_Z);
    expect(rec.magR).toBeCloseTo(-25.5 + 5 * Math.log10(dL * 1e5), 10);
    expect(rec.magG - rec.magR).toBeCloseTo(0.3, 10);
    expect(rec.magI).toBeNaN();
    expect(rec.magU).toBeNaN();
    expect(rec.magZ).toBeNaN();
  });

  it('converts nanomaggy flux to magnitude for BGS: flux 100 → mag 17.5', () => {
    const buf = buildClusteringBuffer(BGS_COLUMNS, [[1n, 150.0, 30.0, 0.2, 100, 100, 100]]);
    const { records, skipped } = parseDesiClustering(buf, 'BGS');
    expect(records.length).toBe(1);
    expect(skipped).toBe(0);
    const rec = records[0]!;
    expect(rec.magG).toBeCloseTo(22.5 - 2.5 * Math.log10(100), 10);
    expect(rec.magR).toBeCloseTo(17.5, 10);
    expect(rec.magI).toBeCloseTo(17.5, 10);
  });

  it('drops BGS rows with non-positive g or r flux and counts them in skipped', () => {
    const buf = buildClusteringBuffer(BGS_COLUMNS, [
      [1n, 150.0, 30.0, 0.2, -1, 100, 100], // g flux negative → dropped
      [2n, 151.0, 31.0, 0.2, 100, 0, 100], // r flux zero → dropped
      [3n, 152.0, 32.0, 0.2, 100, 100, 100], // clean → kept
    ]);
    const { records, skipped } = parseDesiClustering(buf, 'BGS');
    expect(records.length).toBe(1);
    expect(records[0]!.objID).toBe(3n);
    expect(skipped).toBe(2);
  });

  it('keeps BGS rows with non-positive z-band flux, emitting magI = NaN', () => {
    const buf = buildClusteringBuffer(BGS_COLUMNS, [[1n, 150.0, 30.0, 0.2, 100, 100, -5]]);
    const { records, skipped } = parseDesiClustering(buf, 'BGS');
    expect(records.length).toBe(1);
    expect(skipped).toBe(0);
    const rec = records[0]!;
    expect(rec.magG).toBeCloseTo(17.5, 10);
    expect(rec.magR).toBeCloseTo(17.5, 10);
    expect(rec.magI).toBeNaN();
  });

  it('LRG and ELG rows synthesize magnitudes from their tracer-table entries', () => {
    const buf = buildClusteringBuffer(FLUXLESS_COLUMNS, [[7n, 233.0, 32.0, 0.7]]);

    const lrg = parseDesiClustering(buf, 'LRG').records[0]!;
    expect(lrg.magR).toBeCloseTo(syntheticMagR('LRG', 0.7), 10);
    expect(lrg.magG - lrg.magR).toBeCloseTo(DESI_TRACER_DISPLAY.LRG.gMinusR, 10);
    expect(lrg.magI).toBeNaN();

    const elg = parseDesiClustering(buf, 'ELG').records[0]!;
    expect(elg.magR).toBeCloseTo(syntheticMagR('ELG', 0.7), 10);
    expect(elg.magG - elg.magR).toBeCloseTo(DESI_TRACER_DISPLAY.ELG.gMinusR, 10);
    expect(elg.magI).toBeNaN();
  });

  it('emits the GLADE no-orientation fallback shape: axisRatio null, positionAngleDeg null, diameterKpc null', () => {
    const { records } = parseDesiClustering(loadFixture(), 'QSO');
    for (const rec of records) {
      expect(rec.axisRatio).toBeNull();
      expect(rec.positionAngleDeg).toBeNull();
      expect(rec.diameterKpc).toBeNull();
    }
  });

  it('applies the keep predicate before record construction', () => {
    // Reject everything: out-of-cone rows are scoping, not data quality,
    // so they must not appear in either the records OR the skipped count.
    const { records, skipped } = parseDesiClustering(loadFixture(), 'QSO', () => false);
    expect(records.length).toBe(0);
    expect(skipped).toBe(0);
  });

  it('carries TARGETID as objID (bigint) and the tracer classByte', () => {
    const { records } = parseDesiClustering(loadFixture(), 'QSO');
    const rec = records[0]!;
    expect(rec.objID).toBeTypeOf('bigint');
    expect(rec.objID).toBe(QSO_ROW0_TARGETID);
    expect(rec.classByte).toBe(DESI_TRACER_CLASS.QSO);
    expect(rec.classByte).toBe(4);
    expect(rec.parentSurveyByte).toBe(0);
  });

  it('throws when a required column is missing (BGS demands the dered flux columns)', () => {
    // A fluxless table parsed as BGS must fail loudly, naming the column —
    // the requireColumn idiom from parseSdssCsv.
    const buf = buildClusteringBuffer(FLUXLESS_COLUMNS, [[1n, 150.0, 30.0, 0.2]]);
    expect(() => parseDesiClustering(buf, 'BGS')).toThrow(/flux_g_dered/);
  });
});
