/**
 * /api/process — crop the cached source, run StarNet on the cropped
 * region, apply the alpha pass, and write three intermediates:
 *
 *   starless.png   — full resolution, post-StarNet (input to alpha
 *                    pass + cached for /api/process/alpha-only)
 *   starless.webp  — 512² preview
 *   alpha.webp     — 512² preview with alpha channel
 *
 * The full-resolution `full.webp` + `atlas.webp` are NOT written here
 * — those are computed at Export time so re-Process cycles don't pay
 * the encode cost for files the maintainer hasn't committed to yet.
 *
 * `sessionDirOverride` lets tests substitute a fixture root for
 * sessionPath(tmpId); production callers omit it.
 */
import sharp from 'sharp';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { sessionPath } from '../tmpSession.js';
import { runStarnet, type StarnetConfig } from '../starnet.js';
import { applyLuminanceAsAlpha } from '../../../utils/image/applyLuminanceAsAlpha.js';
import { rotatedExtract } from '../cropExtract.js';

const PREVIEW_PX = 512;

export type ProcessBody = {
  tmpId: string;
  crop: { x: number; y: number; width: number; height: number; rotationDeg: number };
  starnet: { stride: number; upsample: boolean };
  alpha: { blackPoint: number; whitePoint: number; gamma: number };
};

export type ProcessResult = {
  starlessPreviewUrl: string;
  alphaPreviewUrl: string;
};

export async function handleProcess(opts: {
  body: ProcessBody;
  starnetConfig: StarnetConfig;
  /** Test hook — defaults to sessionPath(tmpId). */
  sessionDirOverride?: string;
}): Promise<ProcessResult> {
  const { body } = opts;
  // `dir` is the canonical session directory for this request.  In
  // production it is derived from the tmpId (which encodes where the
  // OS placed the tmp tree); in tests it is an injected mkdtempSync
  // directory.  All file I/O below resolves paths relative to `dir`
  // directly — we never call sessionFilePath() — so the handler is
  // honest and testable with any injected root.
  const dir = opts.sessionDirOverride ?? sessionPath(body.tmpId);
  const sourcePath = resolve(dir, 'source.png');
  const croppedPath = resolve(dir, 'cropped.png');
  const starlessPath = resolve(dir, 'starless.png');

  // 1. Crop the full-resolution source.  `rotatedExtract` handles the
  //    happy path (rotation=0, in-bounds rect) and the relaxed cases:
  //    rotated rect, out-of-image rect (transparent fill).
  const pipeline = await rotatedExtract(sourcePath, body.crop);
  const cropped = await pipeline.png().toBuffer();
  writeFileSync(croppedPath, cropped);

  // 2. StarNet (or mock copy).  The mock copies input → output verbatim,
  //    so the downstream alpha pass still runs — the result just looks
  //    like the original (no stars removed).  That's fine for tests that
  //    are asserting on disk artefacts and alpha-pass behaviour.
  await runStarnet({
    input: croppedPath,
    output: starlessPath,
    stride: body.starnet.stride,
    upsample: body.starnet.upsample,
    config: opts.starnetConfig,
  });

  // 3. Apply luminance-as-alpha to the starless PNG.  We work at full
  //    resolution so the alpha mask is sharp; the preview is generated by
  //    downscaling the alpha'd buffer at the end.  We need raw RGBA bytes
  //    because applyLuminanceAsAlpha operates on a Uint8ClampedArray.
  const { data, info } = await sharp(starlessPath)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const rgba = new Uint8ClampedArray(data.buffer, data.byteOffset, data.byteLength);
  applyLuminanceAsAlpha(rgba, info.width, info.height, body.alpha);

  // 4. Encode previews — starless (no alpha pass applied, so the
  //    maintainer can compare before/after) and alpha (post-pass).
  //
  //    We scale to PREVIEW_PX only on the longest edge (`fit: 'inside'`)
  //    so aspect ratio is preserved for non-square crops.  Quality 85
  //    for the opaque starless, 82 + alphaQuality 90 for the alpha WebP.
  const starlessPreview = await sharp(starlessPath)
    .resize(PREVIEW_PX, PREVIEW_PX, { fit: 'inside' })
    .webp({ quality: 85 })
    .toBuffer();
  writeFileSync(resolve(dir, 'starless.webp'), starlessPreview);

  const alphaPreview = await sharp(Buffer.from(rgba.buffer), {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .resize(PREVIEW_PX, PREVIEW_PX, { fit: 'inside' })
    .webp({ quality: 82, alphaQuality: 90 })
    .toBuffer();
  writeFileSync(resolve(dir, 'alpha.webp'), alphaPreview);

  // ?v=<ms> cache-busts the previews — re-Processing rewrites the same
  // URL with different bytes, and the browser would otherwise serve the
  // stale image from cache.
  const v = Date.now();
  return {
    starlessPreviewUrl: `/api/preview/${body.tmpId}/starless.webp?v=${v}`,
    alphaPreviewUrl: `/api/preview/${body.tmpId}/alpha.webp?v=${v}`,
  };
}
