import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * `tests/fixtures/desi/qso_ngc_head6.fits` (9,270 bytes) was generated by
 * the controller on 2026-07-07 via a live 32 KB HTTP range request against
 * DESI DR1's `QSO_NGC_clustering.dat.fits`
 * (https://data.desi.lbl.gov/public/dr1/survey/catalogs/dr1/LSS/iron/LSScats/v1.5/QSO_NGC_clustering.dat.fits,
 * see `tools/utils/io/rawDataRegistry.ts`'s `desi.qso` entry) —
 * primary header + BINTABLE extension header + the first 6 data rows, with
 * the extension's `NAXIS2` card patched from its true (much larger) row
 * count down to `6` so the fixture stays small while keeping every header
 * card and the first 6 rows byte-identical to the upstream file. It is
 * checked in verbatim and must never be regenerated or hand-edited — a
 * byte-for-byte real FITS file is what makes this test worth having; a
 * synthesized one would only test our own assumptions about the format.
 */
const FIXTURE_PATH = join(process.cwd(), 'tests/fixtures/desi/qso_ngc_head6.fits');

export function loadDesiQsoFixture(): ArrayBuffer {
  const bytes = readFileSync(FIXTURE_PATH);
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}
