import { describe, it, expect, vi } from 'vitest';
import { createLabel3DRenderer } from '../../../../../src/services/gpu/renderers/labels3d/label3DRenderer';
import { parseFontMetrics } from '../../../../../src/services/gpu/labelLayout/fontMetrics';
import type { LoadedFontAtlases } from '../../../../../src/@types/rendering/LoadedFontAtlases';
import type { Label3D } from '../../../../../src/@types/rendering/Label3D';
import type { Vec3 } from '../../../../../src/@types/math/Vec3';
// '?static' pulls the LINKED WGSL text (package:: imports resolved), the same
// specifier label3DRenderer.ts itself imports — see wesl-shaders skill gotcha
// #6 for why vitest.config.ts must separately register wesl-plugin for this
// to link rather than fail as a JS parse error.
import vsLinked from '../../../../../src/services/gpu/shaders/labels3d/vertex.wesl?static';
import fsLinked from '../../../../../src/services/gpu/shaders/labels3d/fragment.wesl?static';

// Single uppercase-A glyph — enough for layoutLabel's construction-time pass
// to run without throwing; unmatched characters are silently dropped (see
// labelRenderer.test.ts).
const FIXTURE_METRICS = parseFontMetrics({
  pages: ['x.png'],
  common: { lineHeight: 50, base: 38, scaleW: 512, scaleH: 512 },
  info: { face: 'X', size: 42 },
  distanceField: { fieldType: 'msdf', distanceRange: 4 },
  chars: [
    {
      id: 65,
      x: 0,
      y: 0,
      width: 30,
      height: 40,
      xoffset: 0,
      yoffset: 0,
      xadvance: 25,
      page: 0,
      chnl: 15,
    },
  ],
});

const FIXTURE_ATLASES: LoadedFontAtlases = {
  metricsByFont: { cormorant: FIXTURE_METRICS },
  bitmaps: [],
};

// Mock GPUDevice that records every queue.writeBuffer call, keyed by the
// target buffer's `label` (createBuffer's descriptor), so a test can decode
// exactly what setLabels packed for a given GPU resource — mirrors
// labelRenderer.test.ts / zoneOfAvoidanceRenderer.test.ts's capturing-mock
// pattern, extended to buffer writes.
function newCapturingDevice(writes: Map<string, Float32Array>) {
  return {
    createBindGroupLayout: vi.fn(() => ({})),
    createShaderModule: vi.fn(() => ({
      getCompilationInfo: () => Promise.resolve({ messages: [] }),
    })),
    createPipelineLayout: vi.fn(() => ({})),
    createRenderPipeline: vi.fn(() => ({})),
    createBuffer: vi.fn((desc: GPUBufferDescriptor) => ({
      __label: desc.label as string,
      destroy: vi.fn(),
    })),
    createTexture: vi.fn(() => ({ createView: vi.fn(() => ({})), destroy: vi.fn() })),
    createSampler: vi.fn(() => ({})),
    createBindGroup: vi.fn(() => ({})),
    queue: {
      writeBuffer: vi.fn(
        (
          buffer: { __label?: string },
          _offset: number,
          data: Float32Array,
          _dataOffset = 0,
          size?: number,
        ) => {
          const label = buffer.__label ?? '';
          // Snapshot: the source view is a reused scratch buffer the
          // renderer keeps writing into, so copy the live window now.
          writes.set(label, data.slice(0, size ?? data.length));
        },
      ),
      copyExternalImageToTexture: vi.fn(),
    },
  } as unknown as GPUDevice;
}

const newRenderer = (writes: Map<string, Float32Array>) =>
  createLabel3DRenderer(newCapturingDevice(writes), 'rgba16float', FIXTURE_ATLASES);

// ── TS/WGSL parity twin ─────────────────────────────────────────────────
//
// Mirrors labels3d/vertex.wesl's world-position derivation for the anchor
// point of a glyph quad (corner = (0,0), so the per-corner xAxis/yAxis
// offset drops out). This is a testing.md WGSL/TS-parity keep-rule: the
// twin is exercised against numbers computed BY HAND below, never against
// numbers generated by calling the twin itself — a self-referential
// assertion would be a mirror test, not a check on the shader's formula.
// LIMIT: this is a hand transcription validated by hand arithmetic; nothing
// binds it to the shader text, so an edit to vertex.wesl alone (with this
// twin left untouched) still passes this suite — the user's visual pose on
// the actual GPU output is the net that catches that drift.
const ATLAS_EM_PX = 84;
function cross(a: Vec3, b: Vec3): Vec3 {
  return [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
}
function computeArcAnchorWorldPos(args: {
  center: Vec3;
  planeNormal: Vec3;
  referenceDir: Vec3;
  radiusMpc: number;
  emMpc: number;
  startAngleRad: number;
  repeatIndex: number;
  repeatCount: number;
  localOffsetXAtlasPx: number;
  localOffsetYAtlasPx: number;
}): Vec3 {
  const mpcPerAtlasPx = args.emMpc / ATLAS_EM_PX;
  const binormal = cross(args.planeNormal, args.referenceDir);
  const repeatAngle = (args.repeatIndex * 2 * Math.PI) / args.repeatCount;
  const arcRad = (args.localOffsetXAtlasPx * mpcPerAtlasPx) / args.radiusMpc;
  const theta = args.startAngleRad + repeatAngle - arcRad;
  const lat = -(args.localOffsetYAtlasPx * mpcPerAtlasPx) / args.radiusMpc;
  const dir: Vec3 = [
    Math.cos(theta) * args.referenceDir[0] + Math.sin(theta) * binormal[0],
    Math.cos(theta) * args.referenceDir[1] + Math.sin(theta) * binormal[1],
    Math.cos(theta) * args.referenceDir[2] + Math.sin(theta) * binormal[2],
  ];
  const yAxis = args.planeNormal;
  return [
    args.center[0] + args.radiusMpc * (dir[0] + lat * yAxis[0]),
    args.center[1] + args.radiusMpc * (dir[1] + lat * yAxis[1]),
    args.center[2] + args.radiusMpc * (dir[2] + lat * yAxis[2]),
  ];
}

describe('label3DRenderer placement (WGSL/TS parity)', () => {
  it('a glyph at localOffset.x = 0, repeatIndex = 0, startAngleRad = 0 lands at center + radiusMpc * referenceDir', () => {
    const writes = new Map<string, Float32Array>();
    const r = newRenderer(writes);

    const label: Label3D = {
      id: 'zoa',
      text: 'A',
      font: 'cormorant',
      placement: {
        center: [5, 0, 0],
        planeNormal: [0, 0, 1],
        referenceDir: [1, 0, 0],
        radiusMpc: 10,
        startAngleRad: 0,
      },
      emMpc: 2,
      repeatCount: 3,
      color: [1, 1, 1, 1],
    };
    r.setLabels([label]);

    // Decode the packed per-label storage record (real production CPU
    // code — see label3DRenderer.ts's byte table).
    const storage = writes.get('label3d-storage')!;
    const center: Vec3 = [storage[0]!, storage[1]!, storage[2]!];
    const radiusMpc = storage[3]!;
    const planeNormal: Vec3 = [storage[4]!, storage[5]!, storage[6]!];
    const emMpc = storage[7]!;
    const referenceDir: Vec3 = [storage[8]!, storage[9]!, storage[10]!];
    const startAngleRad = storage[11]!;
    const repeatCount = new Uint32Array(storage.buffer, storage.byteOffset, storage.length)[17]!;

    // Decode the first packed glyph instance record.
    const instances = writes.get('label3d-instances')!;
    const localOffsetXAtlasPx = instances[0]!;
    const localOffsetYAtlasPx = instances[1]!;
    const repeatIndex = new Uint32Array(
      instances.buffer,
      instances.byteOffset,
      instances.length,
    )[9]!;

    // Sanity check on the fixture itself: a single-char 'A' laid out
    // 'center'/'center' has a non-zero pen advance, so its localOffset.x is
    // NOT naturally 0 — pin it to 0 by construction so this test exercises
    // exactly the case the brief names, independent of layoutLabel's glyph
    // metrics.
    expect(localOffsetXAtlasPx).not.toBe(0);
    expect(localOffsetYAtlasPx).not.toBe(0);
    const worldPos = computeArcAnchorWorldPos({
      center,
      planeNormal,
      referenceDir,
      radiusMpc,
      emMpc,
      startAngleRad,
      repeatIndex,
      repeatCount,
      // The case under test: pen-relative offset (0, 0) — the brief's
      // "localOffset.x = 0" implies the anchor, not this fixture's real
      // (nonzero) center/center-aligned glyph offset.
      localOffsetXAtlasPx: 0,
      localOffsetYAtlasPx: 0,
    });

    // Hand-computed: binormal = cross([0,0,1], [1,0,0]) = [0,1,0]; with
    // repeatIndex 0 and startAngleRad 0, theta = 0, so
    // dir = cos(0)*[1,0,0] + sin(0)*[0,1,0] = [1,0,0], lat = 0, and
    // world = [5,0,0] + 10 * [1,0,0] = [15,0,0] = center + radiusMpc * referenceDir.
    expect(worldPos[0]).toBeCloseTo(15, 10);
    expect(worldPos[1]).toBeCloseTo(0, 10);
    expect(worldPos[2]).toBeCloseTo(0, 10);
  });

  // The case above is DEGENERATE for guarding the handedness/sign bugs the
  // formula exists to catch: repeatIndex = 0 makes repeatAngle = 0,
  // localOffset.x = 0 makes arcRad = 0 (so the '-arcRad' sign is inert),
  // and localOffset.y = 0 makes lat = 0 (so its negation is inert) — theta
  // collapses to 0, where sin(theta) = 0 zeroes out the binormal term
  // entirely. Flipping the cross-product order, the '-arcRad' sign, or the
  // lat negation would all still pass that test. This second case pins
  // real, nonzero values through every one of those terms at once.
  it('a non-degenerate glyph (nonzero repeat, arc, and lat terms) lands where the formula, worked by hand, predicts', () => {
    // Chosen so every term reduces to a value with an exact, independently
    // verifiable closed form:
    //   binormal      = cross([0,0,1], [1,0,0]) = [0,1,0]
    //   repeatAngle   = repeatIndex(1) * 2*PI / repeatCount(4) = PI/2
    //   mpcPerAtlasPx = emMpc(10) / ATLAS_EM_PX(84) = 10/84
    //   arcRad        = localOffsetX(84) * mpcPerAtlasPx / radiusMpc(10)
    //                 = 84 * (10/84) / 10 = 10/10 = 1              (radian)
    //   lat           = -localOffsetY(42) * mpcPerAtlasPx / radiusMpc(10)
    //                 = -(42 * 10/84) / 10 = -(5) / 10 = -0.5
    //   theta         = startAngleRad(0) + repeatAngle(PI/2) - arcRad(1)
    //                 = PI/2 - 1
    // Angle-subtraction identity (not the twin's own formula, so this is
    // an independent reduction, not a re-run of the code under test):
    //   cos(PI/2 - 1) = sin(1) ;  sin(PI/2 - 1) = cos(1)
    // sin(1)/cos(1) are standard mathematical constants (radian argument),
    // verifiable against any reference table or calculator:
    //   sin(1) = 0.8414709848078965
    //   cos(1) = 0.5403023058681398
    // So:
    //   dir = cos(theta)*[1,0,0] + sin(theta)*[0,1,0] = [sin(1), cos(1), 0]
    //   yAxis = planeNormal = [0,0,1]
    //   world = [0,0,0] + 10 * ([sin(1), cos(1), 0] + (-0.5)*[0,0,1])
    //         = [10*sin(1), 10*cos(1), -5]
    //         = [8.414709848078965, 5.403023058681398, -5]
    const worldPos = computeArcAnchorWorldPos({
      center: [0, 0, 0],
      planeNormal: [0, 0, 1],
      referenceDir: [1, 0, 0],
      radiusMpc: 10,
      emMpc: 10,
      startAngleRad: 0,
      repeatIndex: 1,
      repeatCount: 4,
      localOffsetXAtlasPx: 84,
      localOffsetYAtlasPx: 42,
    });

    expect(worldPos[0]).toBeCloseTo(8.414709848078965, 10);
    expect(worldPos[1]).toBeCloseTo(5.403023058681398, 10);
    expect(worldPos[2]).toBeCloseTo(-5, 10);
  });
});

describe('label3DRenderer WESL binding parity', () => {
  it('the vertex + fragment stages declare @group(0) bindings 0-3 exactly once each', () => {
    // vertex.wesl owns bindings 0 (Uniforms) and 1 (labels storage); the
    // fragment stage pulls 2 (atlas) and 3 (atlasSampler) in through
    // lib/msdf.wesl's shadeMsdf — a mis-scoped import (e.g. lib/msdf.wesl
    // re-declaring 0/1, or a duplicate declaration reaching either linked
    // module) would surface only as a WebGPU pipeline-creation error the page
    // smoke can't guarantee to hit; this test statically pins the contract
    // both stages' bind group layout depends on.
    const BINDING_RE = /@group\(0\)\s*@binding\((\d+)\)/g;
    const bindings = [...vsLinked.matchAll(BINDING_RE), ...fsLinked.matchAll(BINDING_RE)].map((m) =>
      Number(m[1]),
    );
    expect(new Set(bindings)).toEqual(new Set([0, 1, 2, 3]));
    expect(bindings).toHaveLength(new Set(bindings).size);
  });
});

describe('label3DRenderer (CPU state)', () => {
  it('starts with zero glyphs to draw', () => {
    const r = newRenderer(new Map());
    expect(r.glyphCount()).toBe(0);
  });

  it('counts one glyph per repeat across repeatCount copies', () => {
    const r = newRenderer(new Map());
    r.setLabels([
      {
        id: 'a',
        text: 'A',
        font: 'cormorant',
        placement: {
          center: [0, 0, 0],
          planeNormal: [0, 0, 1],
          referenceDir: [1, 0, 0],
          radiusMpc: 10,
          startAngleRad: 0,
        },
        emMpc: 2,
        repeatCount: 3,
        color: [1, 1, 1, 1],
      },
    ]);
    // One 'A' glyph per repeat.
    expect(r.glyphCount()).toBe(3);
  });

  it('drops glyphs not present in metrics', () => {
    const r = newRenderer(new Map());
    r.setLabels([
      {
        id: 'x',
        // 'A中A' — 'A' is in metrics (id=65), '中' is not (id=20013).
        text: 'A中A',
        font: 'cormorant',
        placement: {
          center: [0, 0, 0],
          planeNormal: [0, 0, 1],
          referenceDir: [1, 0, 0],
          radiusMpc: 10,
          startAngleRad: 0,
        },
        emMpc: 2,
        repeatCount: 1,
        color: [1, 1, 1, 1],
      },
    ]);
    expect(r.glyphCount()).toBe(2);
  });

  it('replaces (not appends) on subsequent setLabels', () => {
    const r = newRenderer(new Map());
    const placement = {
      center: [0, 0, 0] as Vec3,
      planeNormal: [0, 0, 1] as Vec3,
      referenceDir: [1, 0, 0] as Vec3,
      radiusMpc: 10,
      startAngleRad: 0,
    };
    const font: Label3D['font'] = 'cormorant';
    const color: Label3D['color'] = [1, 1, 1, 1];
    r.setLabels([{ id: 'a', text: 'A', font, placement, emMpc: 2, repeatCount: 1, color }]);
    r.setLabels([{ id: 'b', text: 'A', font, placement, emMpc: 2, repeatCount: 3, color }]);
    expect(r.glyphCount()).toBe(3);
  });
});

describe('label3DRenderer colour target + blend', () => {
  it('bakes the given targetFormat and an ADDITIVE blend into the pipeline', () => {
    const renderPipelines: GPURenderPipelineDescriptor[] = [];
    const device = {
      createBindGroupLayout: vi.fn(() => ({})),
      createShaderModule: vi.fn(() => ({
        getCompilationInfo: () => Promise.resolve({ messages: [] }),
      })),
      createPipelineLayout: vi.fn(() => ({})),
      createRenderPipeline: vi.fn((desc: GPURenderPipelineDescriptor) => {
        renderPipelines.push(desc);
        return {};
      }),
      createBuffer: vi.fn(() => ({ destroy: vi.fn() })),
      createTexture: vi.fn(() => ({ createView: vi.fn(() => ({})), destroy: vi.fn() })),
      createSampler: vi.fn(() => ({})),
      createBindGroup: vi.fn(() => ({})),
      queue: { writeBuffer: vi.fn(), copyExternalImageToTexture: vi.fn() },
    } as unknown as GPUDevice;

    // ctx.format-style call: pass a DIFFERENT format than the swap chain
    // would use, so a regression to a hard-coded format fails this test.
    createLabel3DRenderer(device, 'rgba16float', FIXTURE_ATLASES);
    expect(renderPipelines).toHaveLength(1);
    const target = Array.from(renderPipelines[0]!.fragment!.targets!)[0]!;
    expect(target!.format).toBe('rgba16float');
    // Landmine regression guard (shaders/labels3d/fragment.wesl's header):
    // this MUST stay additive, never premultiplied OVER, or the Apple-
    // Silicon HDR dst-alpha coherency bug the header documents returns.
    expect(target!.blend).toEqual({
      color: { srcFactor: 'one', dstFactor: 'one', operation: 'add' },
      alpha: { srcFactor: 'one', dstFactor: 'one', operation: 'add' },
    });
  });
});
