//! Population assembly — the fused port of `buildStars.ts`'s resolve/place
//! stage plus `selectStars.ts`'s set formula, `countClamps`, `deriveGrid`,
//! and `quantizeStar`.
//!
//! ── Why the TS stages are fused here ───────────────────────────────────────
//!
//! The TS build materialises `GaiaSelectedRow[]`, hands it to `selectStars`,
//! then re-associates truncation tags across the dedup via position-array
//! identity. That reference-join exists because two owners (set algebra vs
//! build bookkeeping) share rows across a function boundary. In Rust the
//! subtraction sets (`hipMatched`, `famousGaiaIds`) are both known *before*
//! any Gaia row is processed — they derive from Hipparcos + the cross-match,
//! not from Gaia — so the set formula can be applied inline during the single
//! pass that resolves distances and places stars. Same formula, same counter
//! semantics (the hipMatched test strictly before the famous test, per row),
//! one pass instead of three materialisations. Population order is preserved
//! exactly: Gaia mains in page order, then GCNS-only supplements in GCNS file
//! order, then Hipparcos bright rows — the order every later stable sort's
//! tie-breaking observes.
//!
//! ── GCNS distances arrive already in parsecs ──────────────────────────────
//!
//! The GCNS CSV's `dist_50` column is KILOparsecs; the ×1000 conversion to
//! parsecs happens exactly once at the parse boundary (see the
//! `GcnsRow::dist_pc` docstring in `parse.rs`), so this module — like every
//! consumer of a catalog parser in the repo — speaks parsecs uniformly. The
//! original TS build consumed dist_50 verbatim as pc, cramming the ~217k
//! GCNS-only supplements 1000× too near (visible as the absMag clamp count ≈
//! the supplement population); the TS side carries the same fix.

use crate::format::{
    abs_mag_bin, abs_mag_to_lut_index, bp_rp_bin, bp_rp_to_color_idx, lut_index_to_abs_mag,
    pack_star_record, Grid, STAR_ABSMAG_LEVELS, STAR_COLORIDX_LEVELS,
};
use crate::morton::morton_encode3;
use crate::parse::{GaiaMainRow, GcnsRow, Hip2Row};
use crate::taper::keep_star;
use rayon::prelude::*;
use rustc_hash::{FxHashMap, FxHashSet};

/// Hipparcos-2 bright-star cut: Gaia saturates on stars brighter than this.
pub const HP_BRIGHT_CUT: f64 = 4.0;

/// Maximum heliocentric distance a star may sit at and still join the built
/// population; farther stars are dropped before the grid is derived. Mirror of
/// the TS `MAX_STAR_DISTANCE_PC` (buildStars.ts) — see that constant's docstring
/// for the measured evidence: the population is sharply peaked at the Sun
/// (p99.9 ≈ 11 kpc) but LMC/SMC members + bad-parallax junk stretch the bounding
/// box to ~98 kpc, bloating every fixed-`2^bits` leaf cell 4–8×. Positions are
/// heliocentric parsecs, so a star's distance is `|position|`.
pub const MAX_STAR_DISTANCE_PC: f64 = 12_000.0;

/// Octree grid resolution — 10 bits/axis = 1024³ leaf cells. Fits the locked
/// SKST format with no version bump: a node's mortonIndex is a u32 and 3×10 = 30
/// bits stay inside it; the runtime reads mortonBitsPerAxis + cellEdgePc from the
/// header rather than assuming a resolution.
pub const DEFAULT_MORTON_BITS: u32 = 10;

// FamousStar → Gaia DR3 ids, the non-null gaiaDr3 values of the curated seed
// (data/seeds/famous_stars.seed.json) — the scene-body dedup keys. The array is
// generated by tools/famous/buildFamousStars.ts (the same tool that emits the
// TS render table) so this Rust builder and the TS build subtract the identical
// set from one source of truth, instead of hand-copying a second array.
//
// It is `include!`d rather than declared as its own `mod famous_ids;` so the
// const lands directly in THIS module's namespace, exactly where the
// hand-maintained array used to live: the consumer below reads
// `FAMOUS_STAR_GAIA_IDS` with no `use`, and there is no runtime JSON parse
// (Cargo carries no serde/json dependency by design — hence committed codegen).
include!("famous_ids.generated.rs");

#[derive(Default, Clone, Copy, Debug, PartialEq, Eq)]
pub struct DropCounts {
    pub no_bailer_jones: u64,
    pub hip_non_positive_plx: u64,
    pub famous_subtracted: u64,
    pub hip_gaia_subtracted: u64,
    pub far_distance: u64,
    pub no_photometry: u64,
}

#[derive(Default, Clone, Copy, Debug, PartialEq, Eq)]
pub struct ClampCounts {
    pub abs_mag: u64,
    pub color_idx: u64,
}

/// One deduped population star, pre-quantization (TS `StarInput` + its tag).
pub struct Star {
    pub position: [f64; 3],
    pub abs_mag: f64,
    pub bp_rp: f64,
    pub app_mag: f64,
    pub is_supplement: bool,
}

/// M = m − 5·log10(d_pc) + 5.
#[inline]
fn absolute_magnitude(apparent: f64, dist_pc: f64) -> f64 {
    apparent - 5.0 * dist_pc.log10() + 5.0
}

/// RA/Dec/dist → heliocentric cartesian (equatorial J2000 frame), port of
/// `raDecDistToCartesian`. libm sin/cos here vs V8's fdlibm port may differ
/// by ulps — that is the one accepted source of rare quantization-bin flips
/// the equivalence report tolerates.
#[inline]
fn ra_dec_dist_to_cartesian(ra_deg: f64, dec_deg: f64, dist: f64) -> [f64; 3] {
    let ra = ra_deg * std::f64::consts::PI / 180.0;
    let dec = dec_deg * std::f64::consts::PI / 180.0;
    let cos_dec = dec.cos();
    [dist * cos_dec * ra.cos(), dist * cos_dec * ra.sin(), dist * dec.sin()]
}

pub struct Population {
    pub stars: Vec<Star>,
    pub drops: DropCounts,
    pub clamps: ClampCounts,
}

/// Evaluate the set formula over the parsed inputs:
///
///   stars = ((gaiaPlaced ∪ gcnsOnly) ∖ hipMatched ∖ famous) ∪ (hipBright ∖ famous)
///
/// with the TS counter semantics: per Gaia row, the hipMatched subtraction is
/// tested before the famous one; a bright Hipparcos row is famous only via
/// its cross-matched Gaia id.
pub fn build_population(
    gaia: &[GaiaMainRow],
    gcns: &[GcnsRow],
    hip_rows: &[Hip2Row],
    hip_skipped: u64,
    hip_to_source_id: &FxHashMap<u32, u64>,
) -> Population {
    let famous: FxHashSet<u64> = FAMOUS_STAR_GAIA_IDS.iter().copied().collect();

    // hipMatched: Gaia ids that a PRESENT bright Hipparcos row resolves to.
    let hip_bright: Vec<&Hip2Row> = hip_rows.iter().filter(|r| r.hp_mag < HP_BRIGHT_CUT).collect();
    let hip_matched: FxHashSet<u64> =
        hip_bright.iter().filter_map(|r| hip_to_source_id.get(&r.hip).copied()).collect();

    let gcns_dist: FxHashMap<u64, f64> =
        gcns.iter().map(|r| (r.source_id, r.dist_pc)).collect();

    // Every Gaia main id — including rows later dropped for lacking a
    // distance — so GCNS-only detection matches the TS `mainSourceIds` set.
    let mut main_source_ids: FxHashSet<u64> =
        FxHashSet::with_capacity_and_hasher(gaia.len() * 2, Default::default());
    for row in gaia {
        main_source_ids.insert(row.source_id);
    }

    let mut drops = DropCounts { hip_non_positive_plx: hip_skipped, ..Default::default() };
    let mut stars: Vec<Star> = Vec::with_capacity(gaia.len() + gcns.len() + hip_bright.len());

    // ── Gaia mains, in page order ─────────────────────────────────────────
    // The distance resolve + placement is pure per-row, so it parallelises;
    // the subtraction bookkeeping is three integer counters (order-free
    // sums). Chunked map + ordered flatten keeps the output order identical
    // to the sequential TS loop.
    let chunks: Vec<(Vec<Star>, u64, u64, u64, u64)> = gaia
        .par_chunks(1 << 16)
        .map(|chunk| {
            let mut out = Vec::with_capacity(chunk.len());
            let (mut no_bj, mut no_phot, mut hip_sub, mut famous_sub) = (0u64, 0u64, 0u64, 0u64);
            for row in chunk {
                let dist_pc = row
                    .r_med_photogeo
                    .or(row.r_med_geo)
                    .or_else(|| gcns_dist.get(&row.source_id).copied());
                let Some(dist_pc) = dist_pc else {
                    no_bj += 1;
                    continue;
                };
                // A missing G magnitude (empty CSV cell) parses to NaN at the
                // parse boundary and flows through uncaught — that is
                // deliberate there (see parse.rs). Left uncaught here,
                // `absolute_magnitude(NaN, d)` is NaN, and the abs-mag
                // quantizer's documented NaN semantics map NaN to LUT index 0,
                // the BRIGHTEST bin, un-counted as a clamp: a fake beacon star
                // near Earth. Drop before it can enter the population.
                if !row.g_mag.is_finite() {
                    no_phot += 1;
                    continue;
                }
                // Set formula, hipMatched strictly before famous (a row that
                // is both counts as hipGaiaSubtracted, per the TS comment).
                if hip_matched.contains(&row.source_id) {
                    hip_sub += 1;
                    continue;
                }
                if famous.contains(&row.source_id) {
                    famous_sub += 1;
                    continue;
                }
                out.push(Star {
                    position: ra_dec_dist_to_cartesian(row.ra_deg, row.dec_deg, dist_pc),
                    abs_mag: absolute_magnitude(row.g_mag, dist_pc),
                    bp_rp: row.bp_rp,
                    app_mag: row.g_mag,
                    is_supplement: false,
                });
            }
            (out, no_bj, no_phot, hip_sub, famous_sub)
        })
        .collect();
    for (chunk, no_bj, no_phot, hip_sub, famous_sub) in chunks {
        stars.extend(chunk);
        drops.no_bailer_jones += no_bj;
        drops.no_photometry += no_phot;
        drops.hip_gaia_subtracted += hip_sub;
        drops.famous_subtracted += famous_sub;
    }

    // ── GCNS-only supplements, in GCNS file order ─────────────────────────
    // The outer-edge taper is applied FIRST — before the hipMatched/famous
    // subtractions — so it matches the TS order exactly: there a GCNS row is
    // taper-dropped in the GCNS loop (before it enters `selectStars`), so a
    // taper-dropped row is never counted against any subtraction counter. The
    // decision is a pure hash of `source_id`, taken once here, so every tier
    // sees the same tapered set. `dist_pc` is the already-parsec GCNS distance,
    // equal to `|position|`.
    for row in gcns {
        if main_source_ids.contains(&row.source_id) {
            continue; // contributed only its distance, joined above
        }
        if !keep_star(row.source_id, row.dist_pc, true) {
            continue; // faint dwarf thinned out of the supplement's outer shell
        }
        // Same missing-photometry guard as the Gaia main loop above — see
        // its comment for why an un-caught NaN G magnitude is a fake-beacon
        // bug, not a harmless clamp.
        if !row.g_mag.is_finite() {
            drops.no_photometry += 1;
            continue;
        }
        if hip_matched.contains(&row.source_id) {
            drops.hip_gaia_subtracted += 1;
            continue;
        }
        if famous.contains(&row.source_id) {
            drops.famous_subtracted += 1;
            continue;
        }
        stars.push(Star {
            position: ra_dec_dist_to_cartesian(row.ra_deg, row.dec_deg, row.dist_pc),
            abs_mag: absolute_magnitude(row.g_mag, row.dist_pc),
            bp_rp: row.bp_rp,
            app_mag: row.g_mag,
            is_supplement: true,
        });
    }

    // ── Hipparcos bright patch (Hp < 4.0) ─────────────────────────────────
    for row in &hip_bright {
        if let Some(&sid) = hip_to_source_id.get(&row.hip) {
            if famous.contains(&sid) {
                drops.famous_subtracted += 1;
                continue;
            }
        }
        stars.push(Star {
            position: ra_dec_dist_to_cartesian(row.ra_deg, row.dec_deg, row.dist_pc),
            abs_mag: absolute_magnitude(row.hp_mag, row.dist_pc),
            bp_rp: bv_to_bp_rp(row.bv),
            app_mag: row.hp_mag,
            is_supplement: false,
        });
    }

    // ── Distance cap: drop far outliers before the grid is derived ────────
    // Mirror of the TS `MAX_STAR_DISTANCE_PC` filter (buildStars.ts), applied at
    // the same conceptual seam — after the population is assembled, before the
    // clamps, grid, and octree all read this same `stars` Vec. Capping here keeps
    // the quantization grid tight around the local sample instead of the ~98 kpc
    // box a handful of LMC/SMC + bad-parallax outliers would otherwise force.
    // `retain` preserves population order, which the later stable sorts observe.
    let before_cap = stars.len() as u64;
    let max_dist_sq_pc = MAX_STAR_DISTANCE_PC * MAX_STAR_DISTANCE_PC;
    stars.retain(|s| {
        let [x, y, z] = s.position;
        x * x + y * y + z * z <= max_dist_sq_pc
    });
    drops.far_distance = before_cap - stars.len() as u64;

    // ── Counted clamps over the whole deduped population ──────────────────
    let clamps = stars
        .par_iter()
        .map(|s| {
            let mut c = ClampCounts::default();
            let ia = abs_mag_bin(s.abs_mag);
            if ia < 0.0 || ia > (STAR_ABSMAG_LEVELS - 1) as f64 {
                c.abs_mag = 1;
            }
            let ic = bp_rp_bin(s.bp_rp);
            if ic < 0.0 || ic > (STAR_COLORIDX_LEVELS - 1) as f64 {
                c.color_idx = 1;
            }
            c
        })
        .reduce(ClampCounts::default, |a, b| ClampCounts {
            abs_mag: a.abs_mag + b.abs_mag,
            color_idx: a.color_idx + b.color_idx,
        });

    Population { stars, drops, clamps }
}

/// Gaia DR3 Table 5.9: G_BP − G_RP = f(B−V), Horner form — port of
/// `tools/utils/color/bvToBpRp.ts`.
#[inline]
fn bv_to_bp_rp(bv: f64) -> f64 {
    0.06483 + bv * (1.575 + bv * (-0.7815 + bv * (0.5707 + bv * -0.176)))
}

/// Derive the shared quantization grid from the population bounding box —
/// port of `deriveGrid` (min corner origin, largest span + 1e-9 headroom).
pub fn derive_grid(stars: &[Star], morton_bits_per_axis: u32) -> Grid {
    if stars.is_empty() {
        return Grid { morton_bits_per_axis, cell_edge_pc: 1.0, origin: [0.0; 3] };
    }
    // min/max are associative + commutative over f64 (no NaNs reach here in
    // practice; a NaN would poison TS the same way), so the parallel
    // reduction is order-independent and thread-count-deterministic.
    let (min, max) = stars
        .par_iter()
        .map(|s| (s.position, s.position))
        .reduce(
            || ([f64::INFINITY; 3], [f64::NEG_INFINITY; 3]),
            |(mut lo, mut hi), (a, b)| {
                for k in 0..3 {
                    if a[k] < lo[k] {
                        lo[k] = a[k];
                    }
                    if b[k] > hi[k] {
                        hi[k] = b[k];
                    }
                }
                (lo, hi)
            },
        );
    let extent = (max[0] - min[0]).max(max[1] - min[1]).max(max[2] - min[2]);
    let cells = (1u64 << morton_bits_per_axis) as f64;
    let cell_edge_pc = if extent > 0.0 { extent * (1.0 + 1e-9) / cells } else { 1.0 };
    Grid { morton_bits_per_axis, cell_edge_pc, origin: min }
}

/// One quantized star, carrying everything a tier probe needs: the packed
/// 6-byte record, the Morton leaf cell, the selection sort rank, and the
/// precomputed flux terms for the aggregate mip (flux and flux-weighted
/// position/colour in leaf-cell grid units — computed once here instead of
/// once per probe × 25 probes).
pub struct QuantStar {
    pub morton: u32,
    /// Bit 31 = is-main; low 31 bits = rank (population index for
    /// supplements, brightness rank for mains). Sorting by
    /// `(morton, rank_field)` reproduces the TS per-probe stable sort of
    /// `[supplement…, brightest-k mains]` for every k at once — filtering a
    /// presorted array preserves relative order, which is exactly what a
    /// stable sort of the filtered subset would produce.
    pub rank_field: u32,
    pub record: u64,
    pub flux: f64,
    pub fx: f64,
    pub fy: f64,
    pub fz: f64,
    pub fc: f64,
}

pub const MAIN_BIT: u32 = 1 << 31;

pub struct Quantized {
    /// All stars, sorted by (morton, supplement-before-main, rank).
    pub sorted: Vec<QuantStar>,
    /// Apparent magnitudes of main stars in brightness-rank order — rank r's
    /// appMag; `gCutMag` for a tier of k mains is `main_app_mags[k-1]`.
    pub main_app_mags: Vec<f64>,
    pub supplement_count: u32,
    pub grid: Grid,
}

/// Quantize every population star once and produce the selection-order sort
/// (see `QuantStar::rank_field`). Port of `quantizeStar` + the brightness
/// partition/sort in `buildStarCatalog`.
pub fn quantize_population(stars: &[Star], grid: Grid) -> Quantized {
    let cells = 1i64 << grid.morton_bits_per_axis;

    // Brightness ranks: stable parallel sort of main-star indices by appMag.
    // Stability matters — TS TimSort keeps population order on ties, and the
    // tie order decides which star sits at a tier's truncation boundary.
    let mut main_idx: Vec<u32> = (0..stars.len() as u32)
        .filter(|&i| !stars[i as usize].is_supplement)
        .collect();
    main_idx.par_sort_by(|&a, &b| {
        stars[a as usize]
            .app_mag
            .partial_cmp(&stars[b as usize].app_mag)
            .expect("NaN appMag would make the TS sort unspecified — refuse loudly")
    });
    let main_app_mags: Vec<f64> = main_idx.iter().map(|&i| stars[i as usize].app_mag).collect();
    let mut rank_of: Vec<u32> = vec![0; stars.len()];
    for (rank, &i) in main_idx.iter().enumerate() {
        rank_of[i as usize] = rank as u32 | MAIN_BIT;
    }
    let mut supp_rank = 0u32;
    for (i, s) in stars.iter().enumerate() {
        if s.is_supplement {
            rank_of[i] = supp_rank; // population order among supplements
            supp_rank += 1;
        }
    }

    let mut sorted: Vec<QuantStar> = stars
        .par_iter()
        .enumerate()
        .map(|(i, s)| {
            // Port of `quantizeStar`: cell = clamped floor(rel), offset =
            // clamped floor((rel − cell) · 1024).
            let mut cell = [0u32; 3];
            let mut offset = [0u32; 3];
            let mut grid_pos = [0f64; 3];
            for a in 0..3 {
                let rel = (s.position[a] - grid.origin[a]) / grid.cell_edge_pc;
                let c = (rel.floor() as i64).clamp(0, cells - 1);
                let o = (((rel - c as f64) * 1024.0).floor() as i64).clamp(0, 1023);
                cell[a] = c as u32;
                offset[a] = o as u32;
                // Leaf-cell grid units for the flux centroid, exactly the TS
                // frame: cell + offset/1024.
                grid_pos[a] = c as f64 + o as f64 / 1024.0;
            }
            // Flux the RECORD represents — dequantized stored index, not the raw
            // magnitude — so an aggregate sums exactly what its refined leaves
            // deposit (flux conservation across LOD; see octree.rs / the TS
            // buildStarOctree leaf construction).
            let abs_mag_idx = abs_mag_to_lut_index(s.abs_mag);
            let flux = 10f64.powf(-0.4 * lut_index_to_abs_mag(abs_mag_idx));
            QuantStar {
                morton: morton_encode3(cell[0], cell[1], cell[2]),
                rank_field: rank_of[i],
                record: pack_star_record(
                    offset[0],
                    offset[1],
                    offset[2],
                    abs_mag_idx,
                    bp_rp_to_color_idx(s.bp_rp),
                ),
                flux,
                fx: flux * grid_pos[0],
                fy: flux * grid_pos[1],
                fz: flux * grid_pos[2],
                fc: flux * s.bp_rp,
            }
        })
        .collect();

    // (morton, rank_field) is unique per star (ranks are unique within each
    // class and the class bit separates them), so an unstable parallel sort
    // is still fully deterministic.
    sorted.par_sort_unstable_by_key(|q| ((q.morton as u64) << 32) | q.rank_field as u64);

    Quantized { sorted, main_app_mags, supplement_count: supp_rank, grid }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn no_hip() -> (Vec<Hip2Row>, FxHashMap<u32, u64>) {
        (Vec::new(), FxHashMap::default())
    }

    #[test]
    fn gaia_main_row_with_nan_g_mag_is_dropped_and_counted() {
        // A resolvable distance but a missing (NaN) G magnitude — the empty
        // `phot_g_mean_mag` cell case. Without the guard this row would place
        // a fake beacon star (absMag quantizes NaN to the brightest LUT bin).
        let gaia = vec![GaiaMainRow {
            source_id: 42,
            ra_deg: 10.0,
            dec_deg: 20.0,
            g_mag: f64::NAN,
            bp_rp: 0.7,
            r_med_geo: None,
            r_med_photogeo: Some(20.0),
        }];
        let (hip_rows, hip_to_source_id) = no_hip();
        let pop = build_population(&gaia, &[], &hip_rows, 0, &hip_to_source_id);

        assert_eq!(pop.stars.len(), 0);
        assert_eq!(pop.drops.no_photometry, 1);
    }

    #[test]
    fn gcns_supplement_row_with_nan_g_mag_is_dropped_and_counted() {
        // Same guard on the GCNS-only supplement loop — a row inside the
        // taper start (kept unconditionally by `keep_star`) still must not
        // join the population without a real G magnitude.
        let gcns = vec![GcnsRow {
            source_id: 99,
            ra_deg: 60.0,
            dec_deg: -20.0,
            dist_pc: 10.0,
            g_mag: f64::NAN,
            bp_rp: 1.0,
        }];
        let (hip_rows, hip_to_source_id) = no_hip();
        let pop = build_population(&[], &gcns, &hip_rows, 0, &hip_to_source_id);

        assert_eq!(pop.stars.len(), 0);
        assert_eq!(pop.drops.no_photometry, 1);
    }
}
