/**
 * The fixtures are built with a deliberately shuffled property order and a
 * stray `nx` normal, because the whole point of parsing the header is that
 * Brush's field order is not a constant we may hard-code. Every expected
 * value below is hand-computed, never re-derived from the reader's own
 * expressions.
 */
import { describe, it, expect } from 'vitest';
import { readGaussianPly } from '../../../../tools/scene-recon/splats/readGaussianPly';

/** Brush's own order is `x y z scale_* opacity rot_* f_dc_*`; ours is not. */
const SHUFFLED = [
  'opacity',
  'f_dc_0',
  'f_dc_1',
  'f_dc_2',
  'nx',
  'rot_0',
  'rot_1',
  'rot_2',
  'rot_3',
  'x',
  'y',
  'z',
  'scale_0',
  'scale_1',
  'scale_2',
] as const;

function buildPly(
  properties: readonly string[],
  vertices: readonly (readonly number[])[],
): ArrayBuffer {
  const header =
    'ply\n' +
    'format binary_little_endian 1.0\n' +
    'comment Generated by Brush\n' +
    `element vertex ${vertices.length}\n` +
    properties.map((name) => `property float ${name}\n`).join('') +
    'end_header\n';
  const headerBytes = new TextEncoder().encode(header);
  const stride = properties.length * 4;
  const buffer = new ArrayBuffer(headerBytes.length + vertices.length * stride);
  new Uint8Array(buffer).set(headerBytes);
  const dv = new DataView(buffer);
  vertices.forEach((values, v) => {
    values.forEach((value, p) => {
      dv.setFloat32(headerBytes.length + v * stride + p * 4, value, true);
    });
  });
  return buffer;
}

// opacity, f_dc_0..2, nx, rot_0..3 (scalar-first w,x,y,z), x, y, z, scale_0..2
const VERTEX_A = [
  2.0, 1.0, -3.0, 0.0, 0.0, 0.9, 0.1, 0.2, 0.3, 1.5, -2.25, 10.0, -2.5, -3.0, -1.25,
];
const VERTEX_B = [
  -1.0, 4.0, 0.5, -0.5, 0.0, -0.5, 0.5, -0.5, 0.5, -7.0, 0.5, 3.25, 0.25, -0.5, 1.75,
];

const SHUFFLED_PLY = buildPly(SHUFFLED, [VERTEX_A, VERTEX_B]);

describe('readGaussianPly locates fields by the header, not by Brush field order', () => {
  it('reads positions and log scales from their header-declared offsets', () => {
    const { splats, shDegree } = readGaussianPly(SHUFFLED_PLY);

    expect(splats).toHaveLength(2);
    expect(shDegree).toBe(0);
    expect(splats[0]!.fRest).toBeNull();

    expect(splats[0]!.xM).toBe(1.5);
    expect(splats[0]!.yM).toBe(-2.25);
    expect(splats[0]!.zM).toBe(10.0);
    // Scales stay log — splats.bin stores log too, so no exp() here.
    expect(splats[0]!.logScale).toEqual([-2.5, -3.0, -1.25]);

    // Second vertex proves the stride includes the unused `nx` property.
    expect(splats[1]!.xM).toBe(-7.0);
    expect(splats[1]!.yM).toBe(0.5);
    expect(splats[1]!.zM).toBe(3.25);
    expect(splats[1]!.logScale).toEqual([0.25, -0.5, 1.75]);
  });
});

describe('readGaussianPly applies the sigmoid to opacity', () => {
  it('turns the pre-sigmoid PLY value into a 0..1 probability', () => {
    const { splats } = readGaussianPly(SHUFFLED_PLY);

    // 1/(1+e^-2) = 1/(1+0.1353352832366127) = 0.8807970779778823
    expect(splats[0]!.opacity).toBeCloseTo(0.8807970779778823, 12);
    // 1/(1+e^1) = 1/(1+2.718281828459045) = 0.2689414213699951
    expect(splats[1]!.opacity).toBeCloseTo(0.2689414213699951, 12);
  });
});

describe('readGaussianPly evaluates f_dc to 0..255 RGB via the SH0 formula', () => {
  it('clamps both ends of clamp(0.5 + 0.28209479 * f_dc, 0, 1) * 255', () => {
    const { splats } = readGaussianPly(SHUFFLED_PLY);

    // f_dc 1.0 → 0.5 + 0.28209479 = 0.78209479 → × 255 = 199.43417145
    expect(splats[0]!.dcColor[0]).toBeCloseTo(199.43417145, 5);
    // f_dc -3.0 → 0.5 - 0.84628437 = -0.34628437 → clamps to 0
    expect(splats[0]!.dcColor[1]).toBe(0);
    // f_dc 0.0 → 0.5 → × 255 = 127.5
    expect(splats[0]!.dcColor[2]).toBe(127.5);

    // f_dc 4.0 → 0.5 + 1.12837916 = 1.62837916 → clamps to 1 → 255
    expect(splats[1]!.dcColor[0]).toBe(255);
    // f_dc 0.5 → 0.5 + 0.141047395 = 0.641047395 → × 255 = 163.467085725
    expect(splats[1]!.dcColor[1]).toBeCloseTo(163.467085725, 5);
    // f_dc -0.5 → 0.5 - 0.141047395 = 0.358952605 → × 255 = 91.532914275
    expect(splats[1]!.dcColor[2]).toBeCloseTo(91.532914275, 5);
  });
});

describe('readGaussianPly reorders rot_0..3 from scalar-first to [x, y, z, w]', () => {
  it('moves the leading scalar to the tail', () => {
    const { splats } = readGaussianPly(SHUFFLED_PLY);

    // Fixture wrote w=0.9, x=0.1, y=0.2, z=0.3.
    expect(splats[0]!.rotation[0]).toBeCloseTo(0.1, 6);
    expect(splats[0]!.rotation[1]).toBeCloseTo(0.2, 6);
    expect(splats[0]!.rotation[2]).toBeCloseTo(0.3, 6);
    expect(splats[0]!.rotation[3]).toBeCloseTo(0.9, 6);

    // Fixture wrote w=-0.5, x=0.5, y=-0.5, z=0.5 — signs alone catch a rotate-left.
    expect(splats[1]!.rotation).toEqual([0.5, -0.5, 0.5, -0.5]);
  });
});

describe('readGaussianPly infers shDegree from the f_rest properties', () => {
  const withFRest = (coefficientsPerChannel: number): ArrayBuffer => {
    const fRest = Array.from({ length: coefficientsPerChannel * 3 }, (_unused, k) => `f_rest_${k}`);
    // Values encode their own index so a channel-major slip is unmistakable.
    const values = Array.from({ length: coefficientsPerChannel * 3 }, (_unused, k) => k / 64);
    return buildPly([...SHUFFLED, ...fRest], [[...VERTEX_A, ...values]]);
  };

  it('reports degree 1 and keeps R, G, B coefficients 0..2 channel-major', () => {
    const { splats, shDegree } = readGaussianPly(withFRest(3));

    expect(shDegree).toBe(1);
    // f_rest_0..8 → R = 0,1,2 · G = 3,4,5 · B = 6,7,8, each divided by 64.
    expect(splats[0]!.fRest).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8].map((k) => k / 64));
  });

  it('drops the higher orders of a degree-3 PLY, keeping 3 of each 15', () => {
    const { splats, shDegree } = readGaussianPly(withFRest(15));

    expect(shDegree).toBe(1);
    // Channels start at f_rest_0, f_rest_15, f_rest_30 — not at 0, 3, 6.
    expect(splats[0]!.fRest).toEqual([0, 1, 2, 15, 16, 17, 30, 31, 32].map((k) => k / 64));
  });
});

describe('readGaussianPly rejects PLYs it cannot decode', () => {
  it('throws on an ASCII body, a missing property and a truncated body', () => {
    const ascii = new TextEncoder().encode(
      'ply\nformat ascii 1.0\nelement vertex 1\nproperty float x\nend_header\n1.0\n',
    ).buffer as ArrayBuffer;
    expect(() => readGaussianPly(ascii)).toThrow(/binary_little_endian/);

    const noOpacity = buildPly(
      SHUFFLED.filter((name) => name !== 'opacity'),
      [VERTEX_A.slice(1)],
    );
    expect(() => readGaussianPly(noOpacity)).toThrow(/opacity/);

    expect(() => readGaussianPly(SHUFFLED_PLY.slice(0, SHUFFLED_PLY.byteLength - 8))).toThrow(
      /truncat/i,
    );
  });
});
