/**
 * Tests for Panel.
 *
 * ### Why .test.ts not .test.tsx
 *
 * The project's vitest config runs in the `node` environment with no DOM
 * library installed (see CLAUDE.md for the rationale).  We use
 * `react-dom/server.renderToStaticMarkup` to snapshot the initial markup
 * as a string and assert against it — enough to verify every static branch
 * of the component (default open, defaultOpen=false, title rendering,
 * children rendering, aria-label).  Click-driven toggle is verified
 * manually against the live dev server.
 */

import { describe, expect, it } from 'vitest';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { Panel } from '../../../../src/components/common/Panel/Panel';

describe('Panel', () => {
  it('renders the supplied title', () => {
    const html = renderToStaticMarkup(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY'),
      }),
    );
    expect(html).toContain('STATS');
  });

  it('mounts open by default (aria-expanded="true" + body visible)', () => {
    const html = renderToStaticMarkup(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY_CONTENT'),
      }),
    );
    expect(html).toContain('aria-expanded="true"');
    expect(html).toContain('BODY_CONTENT');
  });

  it('mounts closed when defaultOpen=false (body absent from DOM)', () => {
    const html = renderToStaticMarkup(
      createElement(Panel, {
        title: 'STATS',
        defaultOpen: false,
        children: createElement('span', null, 'BODY_CONTENT'),
      }),
    );
    expect(html).toContain('aria-expanded="false"');
    // Body is conditionally rendered — when closed the children are
    // absent from the DOM (not just CSS-hidden).  See the Panel module
    // header for why.
    expect(html).not.toContain('BODY_CONTENT');
  });

  it('forwards aria-label to the outer wrapper when provided', () => {
    const html = renderToStaticMarkup(
      createElement(Panel, {
        title: 'STATS',
        ariaLabel: 'Render statistics',
        children: createElement('span', null, 'BODY'),
      }),
    );
    expect(html).toContain('aria-label="Render statistics"');
  });

  it('omits the aria-label attribute when not provided', () => {
    const html = renderToStaticMarkup(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY'),
      }),
    );
    expect(html).not.toContain('aria-label=');
  });

  it('wires aria-controls on the button to the body id', () => {
    // The exact id is opaque (generated by useId), but it must match
    // between the button's aria-controls and the body div's id — that
    // contract is what lets screen readers traverse the relationship.
    const html = renderToStaticMarkup(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY'),
      }),
    );
    const controlsMatch = html.match(/aria-controls="([^"]+)"/);
    expect(controlsMatch).not.toBeNull();
    const bodyId = controlsMatch![1];
    expect(html).toContain(`id="${bodyId}"`);
  });
});
