// @vitest-environment jsdom
/**
 * Tests for Panel.
 *
 * The Panel's collapse animation is driven by a CSS-Grid
 * `grid-template-rows` interpolation; the body element stays mounted
 * in both states.  Because CSS-modules class names don't actually
 * carry styles in jsdom, we assert against ARIA attributes — the
 * stable, intent-level contract — rather than CSS-modules-mangled
 * class fragments like `_bodyWrapperOpen_`, so the tests survive any
 * benign rename of the SCSS file.
 */

import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createElement } from 'react';
import { Panel } from '../../../../src/components/common/Panel/Panel';

describe('Panel', () => {
  it('renders the supplied title', () => {
    render(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY'),
      }),
    );
    expect(screen.getByRole('button', { name: /STATS/i })).toBeInTheDocument();
  });

  it('mounts open by default (aria-expanded="true" + body content rendered)', () => {
    render(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY_CONTENT'),
      }),
    );
    expect(
      screen.getByRole('button', { name: /STATS/i }),
    ).toHaveAttribute('aria-expanded', 'true');
    expect(screen.getByText('BODY_CONTENT')).toBeInTheDocument();
  });

  it('mounts closed when defaultOpen=false (body still in DOM)', () => {
    render(
      createElement(Panel, {
        title: 'STATS',
        defaultOpen: false,
        children: createElement('span', null, 'BODY_CONTENT'),
      }),
    );
    expect(
      screen.getByRole('button', { name: /STATS/i }),
    ).toHaveAttribute('aria-expanded', 'false');
    // Body stays mounted in the DOM regardless of open state — the CSS
    // grid-template-rows trick collapses its visual height to zero
    // smoothly.  We verify the *intent* via aria-expanded above and
    // confirm the children still exist in the tree here.
    expect(screen.getByText('BODY_CONTENT')).toBeInTheDocument();
  });

  it('toggles aria-expanded when the title button is clicked', async () => {
    const user = userEvent.setup();
    render(
      createElement(Panel, {
        title: 'STATS',
        defaultOpen: false,
        children: createElement('span', null, 'BODY'),
      }),
    );
    const btn = screen.getByRole('button', { name: /STATS/i });
    expect(btn).toHaveAttribute('aria-expanded', 'false');
    await user.click(btn);
    expect(btn).toHaveAttribute('aria-expanded', 'true');
    await user.click(btn);
    expect(btn).toHaveAttribute('aria-expanded', 'false');
  });

  it('forwards aria-label to the outer wrapper when provided', () => {
    const { container } = render(
      createElement(Panel, {
        title: 'STATS',
        ariaLabel: 'Render statistics',
        children: createElement('span', null, 'BODY'),
      }),
    );
    // The outer wrapper is the first DOM child of our render container.
    const outer = container.firstElementChild as HTMLElement;
    expect(outer).toHaveAttribute('aria-label', 'Render statistics');
  });

  it('omits the aria-label attribute when not provided', () => {
    const { container } = render(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY'),
      }),
    );
    const outer = container.firstElementChild as HTMLElement;
    expect(outer).not.toHaveAttribute('aria-label');
  });

  it('wires aria-controls on the button to the body id', () => {
    // The exact id is opaque (generated by useId), but it must match
    // between the button's aria-controls and the body div's id — that
    // contract is what lets screen readers traverse the relationship.
    render(
      createElement(Panel, {
        title: 'STATS',
        children: createElement('span', null, 'BODY'),
      }),
    );
    const btn = screen.getByRole('button', { name: /STATS/i });
    const controlledId = btn.getAttribute('aria-controls');
    expect(controlledId).toBeTruthy();
    expect(document.getElementById(controlledId!)).not.toBeNull();
  });
});
